// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// Compliance Test Suite Execution on Cuttlefish Virtual Devices.
//
// On error, cleanup VM instances because the GCE plugin can lose connection
// with GCP and VM instance, leaving the instance running and that adds to
// cloud costs.

@Library('android-pipeline-shared') _

cvdPipeline(
    customStages: [
        [
            name: 'CTS execution',
            steps: {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    script { env.CTS_STAGE = 'true' }
                    sh '''
                        ANDROID_VERSION=${ANDROID_VERSION} \
                        CTS_DOWNLOAD_URL="${CTS_DOWNLOAD_URL}" \
                        ./workloads/android/pipelines/tests/cts_execution/cts_initialise.sh
                        CTS_TESTPLAN="${CTS_TESTPLAN}" \
                        CTS_MODULE="${CTS_MODULE}" \
                        CTS_TIMEOUT="${CTS_TIMEOUT}" \
                        SHARD_COUNT="${NUM_INSTANCES}" \
                        ./workloads/android/pipelines/tests/cts_execution/cts_execution.sh
                    '''

                    archiveArtifacts artifacts: 'cts*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
                    archiveArtifacts artifacts: 'android-cts-results/invocation_summary.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
                    archiveArtifacts artifacts: 'android-cts-results/*.zip', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
                }
            }
        ]
    ]
)
